from rest_framework import serializers  # type: ignore
from django.contrib.auth.models import User  # type: ignore
from hospital.models import (
    Doctor, Patient, Appointment, MedicalRecord, 
    Bill, Notification, PharmacyItem, TeleConsultationSession, 
    MeetingParticipant, LabTest, Prescription, PharmacyOrder, UserProfile,
    SupportMessage
)


class SupportMessageSerializer(serializers.ModelSerializer):
    class Meta:
        model = SupportMessage
        fields = '__all__'


class UserProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserProfile
        fields = ['role', 'phone', 'created_at']

class UserSerializer(serializers.ModelSerializer):
    profile = UserProfileSerializer(read_only=True)
    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email', 'profile', 'is_staff', 'is_active']

class StaffUserSerializer(serializers.ModelSerializer):
    """Refined serializer for clinical workforce management."""
    role = serializers.CharField(source='profile.role', read_only=True)
    phone = serializers.CharField(source='profile.phone', read_only=True)
    
    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email', 'role', 'phone', 'is_active', 'date_joined']



class DoctorSerializer(serializers.ModelSerializer):
    user = UserSerializer(read_only=True)  # type: ignore
    get_name = serializers.ReadOnlyField()

    class Meta:
        model = Doctor
        fields = [
            'id', 'user', 'profile_pic', 'address', 'mobile', 'department',
            'qualification', 'experience_years', 'consultation_fee', 'status',
            'available_days', 'bio', 'get_name', 'created_at', 'permanent_meet_link'
        ]


class DoctorCreateSerializer(serializers.ModelSerializer):
    """For creating doctors with user data."""
    username = serializers.CharField(write_only=True)
    password = serializers.CharField(write_only=True)
    first_name = serializers.CharField(write_only=True)
    last_name = serializers.CharField(write_only=True)
    email = serializers.EmailField(write_only=True)

    class Meta:
        model = Doctor
        fields = [
            'username', 'password', 'first_name', 'last_name', 'email',
            'address', 'mobile', 'department', 'qualification', 'experience_years', 'consultation_fee', 'status'
        ]

    def validate_username(self, value):
        if User.objects.filter(username=value).exists():
            raise serializers.ValidationError('This System Alias (Login ID) is already taken.')
        return value

    def validate_email(self, value):
        if User.objects.filter(email=value).exists():
            raise serializers.ValidationError('This Email is already associated with an account.')
        return value

    def create(self, validated_data):
        # Capture credentials for email dispatch before they are popped/hashed
        raw_password = validated_data.get('password')
        username = validated_data.get('username')
        email = validated_data.get('email')
        first_name = validated_data.get('first_name')
        last_name = validated_data.get('last_name', '')

        user = User.objects.create_user(
            username=validated_data.pop('username'),
            password=validated_data.pop('password'),
            first_name=validated_data.pop('first_name'),
            last_name=validated_data.pop('last_name'),
            email=validated_data.pop('email'),
        )
        # Ensure the UserProfile role matches
        from hospital.models import UserProfile
        UserProfile.objects.update_or_create(user=user, defaults={'role': 'doctor'})
        
        # --- Professional Clinical Email Dispatch ---
        subject = "🔐 Welcome to Lifeline HMS - Your Specialist Credentials"
        body = f"""Hello Dr. {first_name} {last_name},

Your clinical account has been successfully generated by the Lifeline Hospital Administration.

--------------------------------------------------
PORTAL ACCESS CREDENTIALS
--------------------------------------------------
System Alias (Login ID): {username}
Temporary Password: {raw_password}
--------------------------------------------------

Please access the clinical terminal and update your password immediately upon first login.

Regards,
Clinical Administration Layer
Lifeline Next-Gen Hospital Management System
"""
        try:
            from django.core.mail import send_mail
            from django.conf import settings
            send_mail(
                subject,
                body,
                settings.DEFAULT_FROM_EMAIL,
                [email],
                fail_silently=False
            )
            # --- In-App Clinical Notification ---
            from hospital.models import Notification
            Notification.objects.create(
                user=user,
                title="🔒 Clinical Account Initialization",
                message=f"Welcome Dr. {first_name}. Your system credentials have been generated and dispatched to {email}. ID: {username}",
                notification_type='system'
            )
        except Exception as e:
            print(f"Notification/Email Dispatch failed: {e}")

        return Doctor.objects.create(user=user, **validated_data)


class PatientSerializer(serializers.ModelSerializer):
    user = UserSerializer(read_only=True)  # type: ignore
    get_name = serializers.ReadOnlyField()
    age = serializers.ReadOnlyField()
    assigned_doctor_name = serializers.SerializerMethodField()

    class Meta:
        model = Patient
        fields = [
            'id', 'user', 'profile_pic', 'address', 'mobile', 'date_of_birth',
            'blood_group', 'symptoms', 'allergies', 'medical_history', 'emergency_contact',
            'assigned_doctor', 'assigned_doctor_name', 'admit_date', 'status', 'risk_level',
            'get_name', 'age', 'created_at',
        ]

    def get_assigned_doctor_name(self, obj):
        if obj.assigned_doctor:
            return obj.assigned_doctor.get_name
        return None


class PatientCreateSerializer(serializers.ModelSerializer):
    """For admitting new patients with a dedicated local user account."""
    username = serializers.CharField(write_only=True)
    password = serializers.CharField(write_only=True)
    first_name = serializers.CharField(write_only=True)
    last_name = serializers.CharField(write_only=True, required=False, allow_blank=True)
    email = serializers.EmailField(write_only=True)

    class Meta:
        model = Patient
        fields = [
            'username', 'password', 'first_name', 'last_name', 'email',
            'address', 'mobile', 'date_of_birth', 'blood_group', 
            'symptoms', 'allergies', 'medical_history', 'emergency_contact',
            'status', 'risk_level', 'assigned_doctor'
        ]

    def validate_username(self, value):
        if User.objects.filter(username=value).exists():
            raise serializers.ValidationError('This Login ID is already taken.')
        return value

    def validate_email(self, value):
        if User.objects.filter(email=value).exists():
            raise serializers.ValidationError('Email already linked to another patient.')
        return value

    def create(self, validated_data):
        user = User.objects.create_user(
            username=validated_data.pop('username'),
            password=validated_data.pop('password'),
            first_name=validated_data.pop('first_name'),
            last_name=validated_data.pop('last_name', ''),
            email=validated_data.pop('email'),
        )
        return Patient.objects.create(user=user, **validated_data)


class AppointmentSerializer(serializers.ModelSerializer):
    patientName = serializers.ReadOnlyField(source='patient.get_name')
    doctorName = serializers.ReadOnlyField(source='doctor.get_name')

    doctor_permanent_link = serializers.ReadOnlyField(source='doctor.permanent_meet_link')
    
    class Meta:
        model = Appointment
        fields = [
            'id', 'patient', 'doctor', 'patientName', 'doctorName',
            'appointment_date', 'appointment_time', 'description', 'status', 'priority', 'notes',
            'meeting_link', 'doctor_permanent_link', 'created_at', 'updated_at'
        ]


class MedicalRecordSerializer(serializers.ModelSerializer):
    patient_name = serializers.SerializerMethodField()
    doctor_name = serializers.SerializerMethodField()

    class Meta:
        model = MedicalRecord
        fields = '__all__'

    def get_patient_name(self, obj):
        return obj.patient.get_name if obj.patient else None

    def get_doctor_name(self, obj):
        return obj.doctor.get_name if obj.doctor else None






class BillSerializer(serializers.ModelSerializer):
    patient_name = serializers.SerializerMethodField()
    service_type = serializers.SerializerMethodField()

    class Meta:
        model = Bill
        fields = '__all__'

    def get_patient_name(self, obj):
        return obj.patient.get_name if obj.patient else None

    def get_service_type(self, obj):
        if obj.medicine_cost > 0: return 'Pharmacy'
        if obj.test_cost > 0: return 'Laboratory'
        if obj.consultation_fee > 0: return 'Consultation'
        return 'General'


class NotificationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Notification
        fields = '__all__'

class PharmacyOrderSerializer(serializers.ModelSerializer):
    class Meta:
        model = PharmacyOrder
        fields = '__all__'




class MeetingParticipantSerializer(serializers.ModelSerializer):
    username = serializers.ReadOnlyField(source='user.username')
    user_name = serializers.ReadOnlyField(source='user.get_full_name')
    
    class Meta:
        model = MeetingParticipant
        fields = ['session', 'user', 'role', 'username', 'user_name', 'joined_at']

class TeleConsultationSessionSerializer(serializers.ModelSerializer):
    patient_name = serializers.ReadOnlyField(source='patient.get_name')
    created_by_name = serializers.ReadOnlyField(source='created_by.get_name')
    created_by_id = serializers.ReadOnlyField(source='created_by.id')
    participants = MeetingParticipantSerializer(many=True, read_only=True)
    doctor_permanent_link = serializers.ReadOnlyField(source='created_by.permanent_meet_link')
    appointment_date = serializers.ReadOnlyField(source='appointment.appointment_date')
    appointment_time = serializers.ReadOnlyField(source='appointment.appointment_time')

    class Meta:
        model = TeleConsultationSession
        fields = [
            'id', 'appointment', 'patient', 'patient_name', 
            'created_by', 'created_by_name', 'created_by_id', 'doctor_permanent_link',
            'token', 'meeting_link', 'status', 'participants', 'created_at',
            'appointment_date', 'appointment_time'
        ]


class LabTestSerializer(serializers.ModelSerializer):
    patient_name = serializers.ReadOnlyField(source='patient.get_name')

    class Meta:
        model = LabTest
        fields = '__all__'


class PrescriptionSerializer(serializers.ModelSerializer):
    patient_name = serializers.ReadOnlyField(source='patient.get_name')
    doctor_name = serializers.ReadOnlyField(source='doctor.get_name')

    class Meta:
        model = Prescription
        fields = '__all__'


class PharmacyItemSerializer(serializers.ModelSerializer):
    status = serializers.ReadOnlyField()

    class Meta:
        model = PharmacyItem
        fields = ['id', 'name', 'category', 'stock_level', 'unit_price',
                  'supplier', 'description', 'expiry_date', 'last_restocked',
                  'created_at', 'status']


class RegisterSerializer(serializers.Serializer):
    """User registration serializer."""
    username = serializers.CharField(max_length=150)
    password = serializers.CharField(min_length=8, write_only=True)
    email = serializers.EmailField()
    first_name = serializers.CharField(max_length=50)
    last_name = serializers.CharField(max_length=50)
    role = serializers.ChoiceField(choices=['patient', 'doctor', 'admin', 'receptionist', 'pharmacist'])
    phone = serializers.CharField(max_length=20, required=False, allow_blank=True)
    address = serializers.CharField(max_length=200, required=False, allow_blank=True)
    department = serializers.CharField(max_length=60, required=False, allow_blank=True)
    symptoms = serializers.CharField(max_length=500, required=False, allow_blank=True)

    def validate_username(self, value):
        if User.objects.filter(username=value).exists():
            raise serializers.ValidationError('Username already exists.')
        return value

    def validate_email(self, value):
        if User.objects.filter(email=value).exists():
            raise serializers.ValidationError('Email already registered.')
        return value

    def validate_phone(self, value):
        if not value:
            return value
            
        if Patient.objects.filter(mobile=value).exists() or \
           Doctor.objects.filter(mobile=value).exists():
            raise serializers.ValidationError('This mobile number is already registered to another account.')
        return value


class DashboardStatsSerializer(serializers.Serializer):
    """Aggregated stats for dashboard."""
    total_doctors = serializers.IntegerField()
    total_patients = serializers.IntegerField()
    total_appointments = serializers.IntegerField()
    pending_appointments = serializers.IntegerField()
    total_revenue = serializers.DecimalField(max_digits=12, decimal_places=2)

from dj_rest_auth.serializers import PasswordResetSerializer  # type: ignore
from django.conf import settings  # type: ignore

class CustomPasswordResetSerializer(PasswordResetSerializer):
    def get_email_options(self):
        return {
            'email_template_name': 'account/email/password_reset_key_message.txt',
            'html_email_template_name': 'account/email/password_reset_key_message.html',
            # This is where your FRONTEND reset password page lives
            'extra_email_context': {
                'password_reset_url': f"{settings.FRONTEND_URL}/reset-password"
            }
        }
