# Generated by Django 5.2.12 on 2026-03-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
