# Generated by Django 5.2.12 on 2026-03-19 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_doctor_is_deleted_patient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pharmacyitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyitem',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacyitem',
            name='category',
            field=models.CharField(choices=[('Analgesic', 'Analgesic'), ('Antibiotic', 'Antibiotic'), ('Antiviral', 'Antiviral'), ('Antifungal', 'Antifungal'), ('Antidiabetic', 'Antidiabetic'), ('Antihypertensive', 'Antihypertensive'), ('Cardiovascular', 'Cardiovascular'), ('Gastrointestinal', 'Gastrointestinal'), ('Neurological', 'Neurological'), ('Antiseptic', 'Antiseptic'), ('Vitamin/Supplement', 'Vitamin/Supplement'), ('Vaccine', 'Vaccine'), ('IV Fluid', 'IV Fluid'), ('Surgical Supply', 'Surgical Supply'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddIndex(
            model_name='pharmacyitem',
            index=models.Index(fields=['category'], name='pharmacy_it_categor_8d92c6_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyitem',
            index=models.Index(fields=['stock_level'], name='pharmacy_it_stock_l_701a5e_idx'),
        ),
    ]
