# Generated by Django 5.2.12 on 2026-03-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_pharmacy_enhanced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
        migrations.AlterField(
            model_name='pharmacyitem',
            name='category',
            field=models.CharField(choices=[('Analgesic', 'Analgesic'), ('Antibiotic', 'Antibiotic'), ('Anti-inflammatory', 'Anti-inflammatory'), ('Antiviral', 'Antiviral'), ('Antifungal', 'Antifungal'), ('Antidiabetic', 'Antidiabetic'), ('Antihypertensive', 'Antihypertensive'), ('Cardiovascular', 'Cardiovascular'), ('Gastrointestinal', 'Gastrointestinal'), ('Neurological', 'Neurological'), ('Antiseptic', 'Antiseptic'), ('Statin', 'Statin'), ('Vitamin/Supplement', 'Vitamin/Supplement'), ('Vaccine', 'Vaccine'), ('IV Fluid', 'IV Fluid'), ('Surgical Supply', 'Surgical Supply'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
