# Generated by Django 5.2.12 on 2026-03-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_medicalrecord_updated_by_medicalrecord_vitals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('nurse', 'Nurse'), ('lab_technician', 'Lab Technician'), ('billing_staff', 'Billing Staff')], default='patient', max_length=20),
        ),
    ]
