# Generated by Django 5.2.12 on 2026-03-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtask',
            name='supervised_by',
        ),
    ]
