# Generated by Django 5.2.12 on 2026-03-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_cleaningtask_supervised_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleaningTask',
        ),
    ]
