# Generated by Django 5.2.12 on 2026-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_teleconsultationsession_meetingparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='permanent_meet_link',
            field=models.URLField(blank=True, help_text='Institutional permanent consultation bridge (e.g. Google Meet)', max_length=500, null=True),
        ),
    ]
