# Generated by Django 5.2.12 on 2026-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_doctor_permanent_meet_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleconsultationsession',
            name='ai_transcript',
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist')], default='patient', max_length=20),
        ),
    ]
