# Generated by Django 5.2.12 on 2026-04-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_bill_guest_mobile_bill_guest_name_alter_bill_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='image_data',
            field=models.TextField(blank=True, help_text='Base64 encoded image data stored directly in DB', null=True),
        ),
    ]
