# Generated by Django 5.2.12 on 2026-04-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
