# Generated by Django 5.2.12 on 2026-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='ai_flag_reason',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='is_abnormal',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('payment', 'Payment'), ('system', 'System'), ('message', 'Message')], default='system', max_length=20),
        ),
        migrations.DeleteModel(
            name='AIDiagnosis',
        ),
    ]
