# Generated by Django 5.2.12 on 2026-04-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_remove_labtest_ai_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
    ]
