# Generated by Django 5.2.12 on 2026-04-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
