# Generated by Django 5.2.12 on 2026-04-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_medicalrecord_prescription_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyorder',
            old_name='pharmacist',
            new_name='assigned_staff',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('receptionist', 'Receptionist')], default='patient', max_length=20),
        ),
    ]
